#!/bin/bash

wget http://dist.neo4j.org/neo4j-community-3.5.8-unix.tar.gz
tar -xvf neo4j-community-3.5.8-unix.tar.gz
echo "dbms.connectors.default_listen_address=0.0.0.0" >> neo4j-community-3.5.8/conf/neo4j.conf
neo4j-community-3.5.8/bin/neo4j-admin set-initial-password neo4j
mkdir -p neo4j-community-3.5.8/data/databases/graph.db
neo4j-community-3.5.8/bin/neo4j-admin load --from=data/petclinic_joa_neo4j.dump --force

